[package]
name = "redid-parse"
version = "0.1.0"
authors = ["ksv1986 <ksv0x07c2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
edid = { version = "0.3" }

[replace]
'edid:0.3.0' = { path = 'edid' }
